<a href="https://colab.research.google.com/github/VISHAL2077/Generative_AI_2025/blob/main/2303a52077_week_1_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

Y_actual = [20, 30, 40, 50, 60]
Y_pred = [20.5, 30.3, 40.2, 50.6, 60.7]

def calculate_metrics(y_actual, y_pred):
    n = len(y_actual)
    absolute_errors = [abs(y_a - y_p) for y_a, y_p in zip(y_actual, y_pred)]
    squared_errors = [(y_a - y_p) ** 2 for y_a, y_p in zip(y_actual, y_pred)]

    mae = sum(absolute_errors) / n
    mse = sum(squared_errors) / n
    rmse = mse ** 0.5

    return mae, mse, rmse

mae_scratch, mse_scratch, rmse_scratch = calculate_metrics(Y_actual, Y_pred)

mae_library = mean_absolute_error(Y_actual, Y_pred)
mse_library = mean_squared_error(Y_actual, Y_pred)
rmse_library = mean_squared_error(Y_actual, Y_pred) ** 0.5

print("Metrics calculated from scratch:")
print(f"Mean Absolute Error (MAE): {mae_scratch}")
print(f"Mean Squared Error (MSE): {mse_scratch}")
print(f"Root Mean Squared Error (RMSE): {rmse_scratch}")

print("\nMetrics calculated using libraries:")
print(f"Mean Absolute Error (MAE): {mae_library}")
print(f"Mean Squared Error (MSE): {mse_library}")
print(f"Root Mean Squared Error (RMSE): {rmse_library}")



Metrics calculated from scratch:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127

Metrics calculated using libraries:
Mean Absolute Error (MAE): 0.4600000000000016
Mean Squared Error (MSE): 0.24600000000000147
Root Mean Squared Error (RMSE): 0.49598387070549127


In [14]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

Y_actual = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
Y_pred = [0, 0, 1, 2, 2, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2]

def calculate_confusion_matrix(y_actual, y_pred, classes):
    matrix = np.zeros((len(classes), len(classes)), dtype=int)
    for a, p in zip(y_actual, y_pred):
        matrix[classes.index(a)][classes.index(p)] += 1
    return matrix

classes = sorted(set(Y_actual))

conf_matrix_scratch = calculate_confusion_matrix(Y_actual, Y_pred, classes)

conf_matrix_library = confusion_matrix(Y_actual, Y_pred)

def calculate_evaluation_metrics(y_actual, y_pred):
    unique_classes = set(y_actual)
    n = len(y_actual)

    true_positives = {cls: 0 for cls in unique_classes}
    false_positives = {cls: 0 for cls in unique_classes}
    false_negatives = {cls: 0 for cls in unique_classes}

    for i in range(n):
        if y_actual[i] == y_pred[i]:
            true_positives[y_actual[i]] += 1
        else:
            false_positives[y_pred[i]] += 1
            false_negatives[y_actual[i]] += 1

    precision = {cls: true_positives[cls] / (true_positives[cls] + false_positives[cls]) if true_positives[cls] + false_positives[cls] > 0 else 0 for cls in unique_classes}
    recall = {cls: true_positives[cls] / (true_positives[cls] + false_negatives[cls]) if true_positives[cls] + false_negatives[cls] > 0 else 0 for cls in unique_classes}
    f1 = {cls: 2 * (precision[cls] * recall[cls]) / (precision[cls] + recall[cls]) if precision[cls] + recall[cls] > 0 else 0 for cls in unique_classes}

    accuracy = sum(1 for i in range(n) if y_actual[i] == y_pred[i]) / n

    return accuracy, precision, recall, f1

accuracy_scratch, precision_scratch, recall_scratch, f1_scratch = calculate_evaluation_metrics(Y_actual, Y_pred)

accuracy_lib = accuracy_score(Y_actual, Y_pred)
precision_lib = precision_score(Y_actual, Y_pred, average=None)
recall_lib = recall_score(Y_actual, Y_pred, average=None)
f1_lib = f1_score(Y_actual, Y_pred, average=None)

print("Confusion Matrix (from scratch):")
print(conf_matrix_scratch)

print("\nConfusion Matrix (using library):")
print(conf_matrix_library)

print("\nMetrics calculated from scratch:")
print(f"Accuracy: {accuracy_scratch}")
print(f"Precision per class: {precision_scratch}")
print(f"Recall per class: {recall_scratch}")
print(f"F1-score per class: {f1_scratch}")

print("\nMetrics calculated using libraries:")
print(f"Accuracy: {accuracy_lib}")
print(f"Precision per class: {list(precision_lib)}")
print(f"Recall per class: {list(recall_lib)}")
print(f"F1-score per class: {list(f1_lib)}")


Confusion Matrix (from scratch):
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Confusion Matrix (using library):
[[2 1 2]
 [2 1 2]
 [2 1 2]]

Metrics calculated from scratch:
Accuracy: 0.3333333333333333
Precision per class: {0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}
Recall per class: {0: 0.4, 1: 0.2, 2: 0.4}
F1-score per class: {0: 0.3636363636363636, 1: 0.25, 2: 0.3636363636363636}

Metrics calculated using libraries:
Accuracy: 0.3333333333333333
Precision per class: [0.3333333333333333, 0.3333333333333333, 0.3333333333333333]
Recall per class: [0.4, 0.2, 0.4]
F1-score per class: [0.36363636363636365, 0.25, 0.36363636363636365]
