<a href="https://colab.research.google.com/github/VISHAL2077/Generative_AI_2025/blob/main/2303A52077_assignment7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
url = "https://drive.google.com/uc?export=download&id=1AcdENlVm5dccNyo_vgdMbneX8YVvH5R3"
df = pd.read_csv(url)
print(df.dtypes)
for col in df.columns:
    if df[col].dtype == 'object':
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object


In [2]:
model = Sequential([
    Dense(8, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(20, activation='relu'),
    Dense(10, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=150, batch_size=64, validation_data=(X_test, y_test))
model.save("diabetes_ann_model.h5")
loaded_model = keras.models.load_model("diabetes_ann_model.h5")
y_pred = (loaded_model.predict(X_test) > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 8s 116ms/step - accuracy: 0.4113 - loss: 0.6430 - val_accuracy: 0.3578 - val_loss: 0.6317
Epoch 2/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.4348 - loss: 0.6422 - val_accuracy: 0.3578 - val_loss: 0.6317
Epoch 3/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.4446 - loss: 0.6433 - val_accuracy: 0.3578 - val_loss: 0.6316
Epoch 4/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.4259 - loss: 0.6417 - val_accuracy: 0.3578 - val_loss: 0.6315
Epoch 5/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4334 - loss: 0.6385 - val_accuracy: 0.3578 - val_loss: 0.6315
Epoch 6/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.4070 - loss: 0.6353 - val_accuracy: 0.3578 - val_loss: 0.6314
Epoch 7/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4312 - loss: 0.6363 - val_accuracy: 0.3578 - val_loss: 0.6313
Epoch 8/150
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - accuracy: 0.4341 - loss: 0.6395 - val_accuracy: 0.3578 - val_loss

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
Test Accuracy: 35.78%

Confusion Matrix:
[[ 0 29  0]
 [ 0 39  0]
 [ 0 41  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        29
           1       0.36      1.00      0.53        39
           2       0.00      0.00      0.00        41

    accuracy                           0.36       109
   macro avg       0.12      0.33      0.18       109
weighted avg       0.13      0.36      0.19       109



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
